SEKOIA-IO/Community

events/smart-descriptions.json
This PR introduces smart descriptions for openssh and fortigate dialects
=> New smart descriptions for openssh and Fortigate events

events/smart-descriptions.json
This small PR introduces two changes:
- reindent the smart-description file for (IMHO) a cleaner json
- one simple netflow smart-description
=> Add smart description for netflows

events/smart-descriptions.json
Initial version of smart descriptions for harfanglab intake.
=> Smart descriptions for harfanglab intake

events/smart-descriptions.json
Add smart descriptions for missing sysmon events and add relationships for the first 10.
=> All sysmon events and first relationships

events/smart-descriptions.json
Add some smart descriptions and relationships:
* Windows Filtering event
* Process Exited
* netfilter
* nginx relationships
=> Add smart descriptions and relationships

events/smart-descriptions.json
Add Smart Description for Fortigate events generated by the protobuf parser.
=> feat(smart-descriptions): add descriptions for protobuf fortigate

events/smart-descriptions.json
Add some Smart Descriptions for Azure intakes
=> feat(smart-descriptions): some descriptions for azure intakes

events/smart-descriptions.json
Add some smart descriptions (including a default one) for Auditbeat
=> feat(smart-descriptions): add auditbeat

events/smart-descriptions.json
This PR introduces smart-descriptions for sample events produced by IONIQ network and detection response product edited by Gatewatcher.
=> Introduce smart-descriptions for AIONIQ

events/smart-descriptions.json
Added smart-descriptions for :
- Traffic
- Threat
=> Feat(Palo Alto): Introduce smart-descriptions

events/smart-descriptions.json
Added smart-descriptions for `fortiproxy` for event types :
- Traffic
- UTM
=> Feat(Fortiproxy): Introduce smart-descriptions

events/smart-descriptions.json
Cover the Threat is mitigated sentinel one type of event
=> Add a single smart description on sentinel one

playbooks/templates/OSINT_to_observables.json, playbooks/templates/Shodan_search_to_observables.json, playbooks/templates/playbooks.json
New templates to help user have guidance to create:
* observables from a Shodan Search
* observables from an OSINT source
=> add Fetch OSINT and Shodan playbook templates

events/smart-descriptions.json
=> feat(stormshield): Add smart-description for connection allowed/blocked.

events/smart-descriptions.json
Add smart-descriptions for McAfee Web Gateway
=> McAfee Web Gateway: add smart-descriptions

events/smart-descriptions.json
=> feat(smart descriptions):  Add Digital Shadows SearchLight

events/smart-descriptions.json
parent task https://github.com/SekoiaLab/platform/issues/26790
=> Fix(Smart Description): Digital Shadows event.dialect had the wrong value

playbooks/templates/DigitalShadows_SearchLight_fetch_alerts.json
Replace event by event**s** when transmitting the list of event
Parent task https://github.com/SekoiaLab/platform/issues/24603
=> fix(Digital Shadows Playbook Template): A list of events should be transmitted with the argument "events".

events/smart-descriptions.json
replace url.domain with destination.ip in mcafee web gateway smartdescriptions
=> Smartdescription: update mcafee web gateway smartdescription

playbooks/templates/playbooks.json
Add workspaces to the index of playbooks templates
=> PlaybookTemplates: add workspaces

events/smart-descriptions.json
Related issue https://github.com/SekoiaLab/platform/issues/27309
=> Feat(Smart Description): Add 1 smart description for Harfanglab

events/smart-descriptions.json
Related issue https://github.com/SekoiaLab/platform/issues/26779
=> feat(Smart Description) Add Vade M365

events/smart-descriptions.json
This Smart Description is a copy/paste from the Nginx one.
Successfully Tested on production with :
```kv
document.cookie = "event-smart-descriptions=https://raw.githubusercontent.com/SEKOIA-IO/Community/632d795272be77b0c9b90d6e05b124f3a9e06f0a/events/smart-descriptions.json"
```
=> feat(Smart Descriptions): Add Cisco WSA.

scripts/mars_stealer_c2_extractor.py
Standalone python script to extract Mars Stealer configuration.
- `r2pipe==1.6.5`
- `cryptography==3.3.2`
```
python3 scripts/mars_stealer_c2_extractor.py --help                          
usage: Mars Stealer C2 configuration extractor [-h] [-a] [-d DIRECTORY] [-f FILE] [-v]
optional arguments:
-h, --help            show this help message and exit
-a, --all             Directory name used to test extraction several samples
-d DIRECTORY, --directory DIRECTORY
path to the directory that contains samples
-f FILE, --file FILE  File path to the sample
-v, --verbose         Activate verbose mode
```
To test the C2 extraction, you can use this sample from [tria.ge, sha256sum:2d299fcdf7562306634b74f187b445ad17ca07495d2a36ffca86c7425a7982db](https://tria.ge/220331-l1mh3saah3), be careful the …
=> mars stealer configuration extractor

events/smart-descriptions.json
Tested on production with:
```
document.cookie = "event-smart-descriptions=https://raw.githubusercontent.com/SEKOIA-IO/Community/a7bda72950c5d124744f034d05d9dcfe96d76454/events/smart-descriptions.json"
```
=> feat(Smart Descriptions): Add Office 365.

playbooks/templates/imperva_waf_fetch_logs.json
Removed unwanted comma breaking front
=> fix(playbook-templates): fix imperva

events/smart-descriptions.json
fix errors in fortiproxy smart-descriptions
=> fix(smart-descriptions): fix fortiproxy smart-descriptions

events/smart-descriptions.json
fix for https://github.com/SekoiaLab/platform/issues/27107#issuecomment-1106624258
=> feat(S1/DeepVisibility): Add Smart Description for process exited.

events/smart-descriptions.json
add smartdescription for Imperva events
=> Add smart description for Imperva Waf events

playbooks/templates/imperva_waf_fetch_logs.json
Use files to forward events from the trigger to the action.
=> change Imperva playbook template

playbooks/templates/forward_vadesecure_records.json
Hello SEKOIA.IO
Here a proposition of a little correction for this Playbook template.
As usual, playbooks are awesome !
Best regards,
=> Playbook correction

events/smart-descriptions.json
Add Smartdescription for cybereason events
=> SmartDescription: add smartdescription for CybeReason MalOp events

playbooks/templates/urgency_to_0_on_rejected.json
Hello Sekoia,
Here is a proposition, to update this trigger for this playbook, to use the dedicated trigger for this usage and not the general one.
This work have to be done on every XDR playbook (I will try to do as much I can during Jully)
Best regards
=> Change trigger for urgency playbook

IOCs/roamingmantis/roaming_mantis_iocs_20220718.csv
Add IoCs file related to the Roaming Mantis blog post (https://blog.sekoia.io/ongoing-roaming-mantis-smishing-campaign-targeting-france/)
=> feat(roamingmantis): add Roaming Mantis IOCs

playbooks/templates/playbooks.json
Add Slack notification template in playbooks.json
=> Feature(playbook-template): add slack notification

playbooks/templates/OSINT_to_observables.json, playbooks/templates/Shodan_search_to_observables.json, playbooks/templates/Tranco_top_domains_to_observables.json, playbooks/templates/get_data_and_enrich_with_cloudflare.json, playbooks/templates/playbooks.json
harmonize tags for playbooks for TIP
=> harmonize tags for playbooks for TIP

playbooks/templates/playbooks.json
Add a missing template playbook in the index
=> Playbooks: add the okta playbook template in the index

sigma_rules/host/correlation_html_smuggling.yml, sigma_rules/host/correlation_iso-lnk_infection_chain.yml
Two exemples of correlation rules to detect infection chains.
=> feat(sigma_rules): adding infection chain correlation rules

IOCs/DarkGate/scripts/AV_checked.txt, IOCs/DarkGate/scripts/DarkGate-C2-communication-deobfuscator.py, IOCs/DarkGate/scripts/action-id-documentations.md
Add this three documents:
- List of AntiVirus solution checked by DarkGate
- Table containing the DarkGate action id and what it does on infected host
- A script to deobfuscate DarkGate HTTP communication
=> Add DarkGate documents

IOCs/DiceLoader/scripts/ReflectiveDLLInjection.h, IOCs/DiceLoader/scripts/extractor.py, IOCs/DiceLoader/scripts/fake_c2_tcp_server.py
Add DiceLoader scripts:
- Configuration extractor
- Fake tcp server
- C header ingestible by IDA to type the Reflective DLL Injection module
=> (feat)/diceloader

IOCs/pikabot/pikabot_iocs_20240603.csv
Add IoCs related to the PikaBot blogpost (https://blog.sekoia.io/pikabot-a-guide-to-its-deep-secrets-and-operations/).
=> feat(pikabot): add PikaBot IoCs

scripts/test_forwarder.bash
This script will be used by the support team to collect information to troubleshoot the Sekoia Forwarder
=> feat(test-forwarder): add script for testing forwarder

sigma_rules/cloud/aws_ec2_enable_serial_console_access.yml, sigma_rules/cloud/aws_ec2_subnet_deleted.yml, sigma_rules/cloud/aws_iam_password_policy_updated.yml, sigma_rules/cloud/aws_route53_transfer_lock_disabled.yml, sigma_rules/cloud/aws_s3_bucket_replication.yml
Sharing rules for AWS, used in the upcoming blogpost with Mitigant.
=> feat(sigma_rules): AWS rules for Sekoia.io/Mitigant blogpost

IOCs/I2PRAT/I2PRAT_iocs_20250211.csv, IOCs/I2PRAT/scripts/ida_hashes_extraction.py, IOCs/I2PRAT/scripts/resolve_hashes.py
Add I2PRAT IoC related to the blog publication and add the script to resolve the loader hash (IDA script + Dumpulator)
=> (I2PRAT)/ioc_and_scripts

sigma_rules/host/attrib_hiding_files.yml, sigma_rules/host/correlation_iso-lnk_chain.yml, sigma_rules/host/correlation_lnk-hta_infection_chain.yml, sigma_rules/host/mshta_suspicious_child.yml, sigma_rules/host/powershell_suspicious_keywords.yml, sigma_rules/network/dynamic_dns_domain.yml, sigma_rules/network/email_suspicious_attachment_received.yml
Sigma rules mentionned in the coming blogpost.
=> feat(sigma_rules): Windows / Network rules for Infection chain madness blogpost
